### ISSUE TITLE
3.0.2

### ISSUE THREAD

**Issue by DerzhavaToday** [justingreerbbi/wordpress-oauth-server#26]
Version 3.0.2

When trying to authenticate I've received the following error:

    "An unsupported scope was requested"

I manually added "auth" scope to the oauth_scopes and set scope field in oauth_clients table to "auth" and now receiving the following error:

    "Not a valid access token"

Is there any way to configure scopes in the WordPress OAuth Server plugin?

**Comment by justingreerbbi** [comment]
Currently the plugin does not currently support scopes fully. Now when I say fully, you can not add a scope when adding a client as well as the API is not extendable via an API.

In order to use a scope it has to be registered. Check out line 92(ish) of file `/library/class-wo-api.php`. Add the scope you are trying to use there.

**Comment by DerzhavaToday** [comment]
Thank you.

The problems has been solved by:
1) passing "basic" scope
2) disabling bacis authorization on WordPress website
