### ISSUE TITLE
400 Cannot Post at oauth/token

### ISSUE THREAD

**Issue by stevenmwade** [justingreerbbi/wordpress-oauth-server#34]
I am authenticating through Wordpress using Electron and the setup for my test site works, but the production site gives a 400 cannot post at oauth/token. The call to oauth/code works, but oauth/token does not. The only difference I can see from the WP Oauth Server is the Running CGI says, "Header 'Authorization Basic' may not work as expected". I can't seem to find anything in the documentation on what causes this or even referencing the Running CGI or what this description could even mean. Something on Wordpress must trigger it, but it's a mystery as to what does.

**Comment by justingreerbbi** [comment]
My apologies for the late response. The 400 and CGI may be due to CGI not passing the needed auth header correctly. This is a know issue with server config and how CGI works. The solution would be to post client_id and client_secret in the body along with the request or use a htacces trick. You can see how to modify the htacces file at https://wp-oauth.com/knowledge-base/requirements/ under "Things to Note"

**Comment by justingreerbbi** [comment]
Closing due to age. If you think there is still an issue, please open a new issue.
Thanks
